rvm:
- 2.2.3
cache: bundler
sudo: false
services:
  - postgresql
addons:
  postgresql: '9.3'
before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:create
- bundle exec rake db:schema:load
