# Add configuration values below, rename the file to application.yml and save.

LINKEDIN_KEY:
LINKEDIN_SECRET:

AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:

development:
  AWS_BUCKET:

production:
  AWS_BUCKET: